name: jsonc_parser
sdkPath: .dvm/dart_sdk

packages:
  - packages/*

command:
  bootstrap:
    environment:
      sdk: ^3.3.3
    dev_dependencies:
      yumemi_lints: ^1.7.0

ide:
  intellij:
    # Disabling IntelliJ's automatic configuration.
    # This is to support different build configurations for environments.
    enabled: false
